const jobs = [
    // 1-10: Big Tech & MNCs
    {
        id: 1,
        title: "Software Engineer Intern",
        company: "Google",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "C++", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹45k–₹80k/month Internship",
        applyUrl: "https://careers.google.com",
        description: "Join our core engineering team to build scalable systems. You will work on real-world problems and gain exposure to massive scale distributed systems. Strong problem-solving skills required."
    },
    {
        id: 2,
        title: "Systems Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Communication"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3.6–5 LPA",
        applyUrl: "https://www.infosys.com/careers",
        description: "Excellent opportunity for fresh graduates to start their career with a global leader. Comprehensive training program included. Candidates must have a strong academic record."
    },
    {
        id: 3,
        title: "Analyst - Cloud Services",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["AWS", "Azure", "Python"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www2.deloitte.com/ui/en.html",
        description: "Work with global clients to implement cloud solutions. You will be part of a dynamic team solving complex business problems using cloud technologies."
    },
    {
        id: 4,
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4.5–6.5 LPA",
        applyUrl: "https://www.accenture.com/in-en/careers",
        description: "Develop and maintain enterprise-grade applications. Collaborative environment with opportunities for continuous learning and growth."
    },
    {
        id: 5,
        title: "Programmer Analyst Trainee",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ".NET, C#, SQL Server",
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "4–5.5 LPA",
        applyUrl: "https://careers.cognizant.com",
        description: "Entry-level role for aspiring developers. You will undergo training in full-stack development and work on live projects."
    },
    {
        id: 6,
        title: "Application Development Associate",
        company: "Sapient",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Node.js", "MongoDB"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.publicissapient.com/careers",
        description: "Looking for a MERN stack developer to join our digital transformation team. Experience with REST APIs and modern frontend frameworks is essential."
    },
    {
        id: 7,
        title: "R&D Intern",
        company: "Oracle",
        location: "Bangalore",
        mode: "Ofsite",
        experience: "Fresher",
        skills: ["Java", "Cloud Infrastructure", "Linux"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹50k/month Internship",
        applyUrl: "https://www.oracle.com/corporate/careers",
        description: "Internship opportunity in our Oracle Cloud Infrastructure (OCI) team. Work on low-level systems programming and high-performance computing."
    },
    {
        id: 8,
        title: "Software Developer 1",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Distributed Systems", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "18–24 LPA",
        applyUrl: "https://www.flipkartcareers.com",
        description: "Solve complex e-commerce scale problems. We are looking for engineers who love coding and have a deep understanding of system design."
    },
    {
        id: 9,
        title: "SDE I",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["C++", "Java", "DynamoDB"],
        source: "Amazon.jobs",
        postedDaysAgo: 0,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.amazon.jobs",
        description: "Build the future of commerce. Join a team where you can own your code from design to production. Experience with AWS services is a plus."
    },
    {
        id: 10,
        title: "Technical Support Engineer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Networking", "Linux", "Communication"],
        source: "Zoho Careers",
        postedDaysAgo: 6,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.zoho.com/careers",
        description: "Provide technical support to our global customer base. Deep dive into product features and help resolve complex technical issues."
    },

    // 11-20: Startups & Unicorns
    {
        id: 11,
        title: "Frontend Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–18 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Build payment interfaces used by millions. We value code quality, performance, and user experience above all."
    },
    {
        id: 12,
        title: "Product Analyst Intern",
        company: "Cred",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Python", "Data Visualization"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹30k/month Internship",
        applyUrl: "https://careers.cred.club",
        description: "Analyze user behavior and product metrics. Work closely with product managers to drive data-driven decision making."
    },
    {
        id: 13,
        title: "Backend Developer",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Go", "Java", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "15–22 LPA",
        applyUrl: "https://careers.swiggy.com",
        description: "Scale our delivery platform to handle millions of orders. Experience with high-concurrency systems is highly desirable."
    },
    {
        id: 14,
        title: "Android Developer",
        company: "PhonePe",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "Jetpack Compose"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "14–20 LPA",
        applyUrl: "https://www.phonepe.com/careers",
        description: "Build the next generation of payments on Android. Strong knowledge of Kotlin and Android architecture patterns required."
    },
    {
        id: 15,
        title: "Full Stack Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "Node.js", "PostgreSQL"],
        source: "Internshala",
        postedDaysAgo: 0,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://www.zomato.com/careers",
        description: "Work on exciting new features for our food delivery app. Great learning environment with mentorship from senior engineers."
    },
    {
        id: 16,
        title: "Data Science Intern",
        company: "Meesho",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Pandas", "Machine Learning"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹40k/month Internship",
        applyUrl: "https://meesho.io/careers",
        description: "Apply ML to real-world e-commerce problems. You'll work on recommendation engines, fraud detection, and more."
    },
    {
        id: 17,
        title: "QA Engineer (Automation)",
        company: "Dream11",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Java", "Appium"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "10–15 LPA",
        applyUrl: "https://careers.dream11.com",
        description: "Ensure the quality of our gaming platform. Write automated tests for web and mobile applications."
    },
    {
        id: 18,
        title: "DevOps Engineer",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Linux", "Docker", "Kubernetes"],
        source: "Zerodha Careers",
        postedDaysAgo: 7,
        salaryRange: "12–18 LPA",
        applyUrl: "https://zerodha.com/careers",
        description: "Manage our infrastructure and deployment pipelines. We are a FOSS-first company, so familiarity with open source tools is a must."
    },
    {
        id: 19,
        title: "Design Intern",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹20k/month Internship",
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Assist in designing clean and intuitive user interfaces. Work closely with the design and product teams."
    },
    {
        id: 20,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Solidity", "Ethereum", "Smart Contracts"],
        source: "Web3.career",
        postedDaysAgo: 1,
        salaryRange: "20–35 LPA",
        applyUrl: "https://polygon.technology/careers",
        description: "Build scalable dApps on the Polygon network. Deep understanding of EVM and smart contract security is required."
    },

    // 21-30: Service Based & Misc
    {
        id: 21,
        title: "Java Developer",
        company: "Wipro",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "Spring", "Hibernate"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "5–8 LPA",
        applyUrl: "https://careers.wipro.com",
        description: "Backend development for banking clients. Responsible for maintaining and upgrading existing legacy systems."
    },
    {
        id: 22,
        title: "SAP Consultant",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SAP ABAP", "Fiori"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www.capgemini.com/careers",
        description: "Implementation and support of SAP modules. Client-facing role requiring good functional and technical knowledge."
    },
    {
        id: 23,
        title: "Network Engineer",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["CCNA", "Networking", "Python"],
        source: "Cisco Jobs",
        postedDaysAgo: 1,
        salaryRange: "8–12 LPA",
        applyUrl: "https://jobs.cisco.com",
        description: "Join our networking engineering team. Work on next-gen routing and switching products."
    },
    {
        id: 24,
        title: "Data Analyst",
        company: "Mu Sigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["R", "Statistics", "Excel"],
        source: "Campus",
        postedDaysAgo: 5,
        salaryRange: "5–7 LPA",
        applyUrl: "https://www.mu-sigma.com/careers",
        description: "Solve business problems using data analytics. Intensive training provided on data science and decision sciences."
    },
    {
        id: 25,
        title: "Salesforce Developer",
        company: "Salesforce",
        location: "Hyderabad",
        mode: "Remote",
        experience: "1-3",
        skills: ["Apex", "Lightning Web Components"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "15–20 LPA",
        applyUrl: "https://www.salesforce.com/company/careers",
        description: "Develop custom solutions on the Salesforce platform. Certification in Salesforce development is a plus."
    },
    {
        id: 26,
        title: "System Administrator",
        company: "HCL Tech",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Windows Server", "Active Directory", "VMware"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.hcltech.com/careers",
        description: "Manage IT infrastructure for enterprise clients. Shift work may be required."
    },
    {
        id: 27,
        title: "Manual Tester",
        company: "TCS",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Gira", "STLC", "SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.5–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Execute test cases and report bugs. Collaborative role working closely with development teams."
    },
    {
        id: 28,
        title: "Graduate Engineer Trainee",
        company: "L&T Technology Services",
        location: "Baroda",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Embedded C", "Microcontrollers"],
        source: "Campus",
        postedDaysAgo: 2,
        salaryRange: "4–5.5 LPA",
        applyUrl: "https://www.ltts.com/careers",
        description: "Embedded systems development for automotive clients. Knowledge of RTOS and CAN protocol is beneficial."
    },
    {
        id: 29,
        title: "Frontend Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Ember.js", "JavaScript", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.freshworks.com/company/careers",
        description: "Build beautiful and responsive UIs for our SaaS products. We focus on craftsmanship and user delight."
    },
    {
        id: 30,
        title: "Cyber Security Analyst",
        company: "Palo Alto Networks",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Network Security", "Python", "SIEM"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "14–22 LPA",
        applyUrl: "https://jobs.paloaltonetworks.com",
        description: "Analyze and respond to security threats. Work with cutting-edge security technologies."
    },
    // Adding 30 more to reach 60...
    { id: 31, title: "React Developer", company: "Juspay", location: "Bangalore", mode: "Onsite", experience: "1-3", skills: ["React", "PureScript", "Haskell"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "18–25 LPA", applyUrl: "https://juspay.in/careers", description: "Build high-performance payment SDKs. Functional programming enthusiasts preferred." },
    { id: 32, title: "Python Developer", company: "PhysicsWallah", location: "Noida", mode: "Onsite", experience: "1-3", skills: ["Django", "FastAPI", "AWS"], source: "Indeed", postedDaysAgo: 2, salaryRange: "8–14 LPA", applyUrl: "https://www.pw.live", description: "Backend development for our ed-tech platform. Scale APIs to handle millions of students." },
    { id: 33, title: "Operations Intern", company: "Uber", location: "Hyderabad", mode: "Hybrid", experience: "Fresher", skills: ["SQL", "Excel", "Analytics"], source: "LinkedIn", postedDaysAgo: 5, salaryRange: "₹35k/month Internship", applyUrl: "https://www.uber.com/careers", description: "Support city operations team with data analysis and process optimization." },
    { id: 34, title: "SDE Intern", company: "Tower Research", location: "Gurgaon", mode: "Onsite", experience: "Fresher", skills: ["C++", "Low Latency"], source: "Campus", postedDaysAgo: 1, salaryRange: "₹1L/month Internship", applyUrl: "https://www.tower-research.com", description: "Work on ultra-low latency trading platforms. Exceptional C++ skills required." },
    { id: 35, title: "Golang Developer", company: "Gojek", location: "Bangalore", mode: "Remote", experience: "1-3", skills: ["Go", "gRPC", "Kafka"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "20–30 LPA", applyUrl: "https://www.gojek.io/careers", description: "Build super-app infrastructure. Experience with distributed systems is a must." },
    { id: 36, title: "iOS Developer", company: "Cure.fit", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Swift", "iOS", "UIKit"], source: "LinkedIn", postedDaysAgo: 6, salaryRange: "12–18 LPA", applyUrl: "https://www.cure.fit/careers", description: "Develop health and fitness features for our iOS app." },
    { id: 37, title: "Graphic Designer", company: "Nykaa", location: "Mumbai", mode: "Onsite", experience: "0-1", skills: ["Photoshop", "Illustrator"], source: "Naukri", postedDaysAgo: 2, salaryRange: "4–6 LPA", applyUrl: "https://www.nykaa.com/careers", description: "Create visual assets for marketing campaigns and social media." },
    { id: 38, title: "Data Engineer", company: "Fractal", location: "Mumbai", mode: "Hybrid", experience: "1-3", skills: ["Spark", "Hadoop", "Python"], source: "LinkedIn", postedDaysAgo: 4, salaryRange: "10–15 LPA", applyUrl: "https://fractal.ai/careers", description: "Build data pipelines for large scale analytics." },
    { id: 39, title: "UI Developer", company: "HDFC Bank", location: "Mumbai", mode: "Onsite", experience: "1-3", skills: ["Angular", "JavaScript"], source: "Naukri", postedDaysAgo: 7, salaryRange: "6–10 LPA", applyUrl: "https://www.hdfcbank.com", description: "Develop internal banking applications. Angular expertise required." },
    { id: 40, title: "Technical Writer", company: "Red Hat", location: "Pune", mode: "Remote", experience: "1-3", skills: ["Markdown", "Git", "Linux"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "8–12 LPA", applyUrl: "https://www.redhat.com/en/jobs", description: "Write technical documentation for enterprise open source software." },
    { id: 41, title: "Intern - Engineering", company: "Qualcomm", location: "Hyderabad", mode: "Onsite", experience: "Fresher", skills: ["C", "Embedded Systems", "Computer Architecture"], source: "Campus", postedDaysAgo: 3, salaryRange: "₹45k/month Internship", applyUrl: "https://qualcomm.com/careers", description: "Work on mobile chipset software and firmware." },
    { id: 42, title: "Site Reliability Engineer", company: "LinkedIn", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "Linux", "Automation"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "20–30 LPA", applyUrl: "https://linkedin.com/careers", description: "Keep LinkedIn up and running. Focus on reliability and automation." },
    { id: 43, title: "Business Analyst", company: "McKinsey", location: "Gurgaon", mode: "Hybrid", experience: "0-1", skills: ["Analysis", "Presentation", "Excel"], source: "LinkedIn", postedDaysAgo: 5, salaryRange: "12–18 LPA", applyUrl: "https://www.mckinsey.com/careers", description: "Analyze client data and present strategic insights." },
    { id: 44, title: "React Native Developer", company: "CoinSwitch", location: "Bangalore", mode: "Remote", experience: "1-3", skills: ["React Native", "Mobile Dev"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "15–25 LPA", applyUrl: "https://coinswitch.co/careers", description: "Build our crypto trading mobile app for Android and iOS." },
    { id: 45, title: "QA Automation", company: "Paytm", location: "Noida", mode: "Onsite", experience: "1-3", skills: ["Java", "TestNG", "Rest Assured"], source: "Naukri", postedDaysAgo: 1, salaryRange: "8–12 LPA", applyUrl: "https://paytm.com/careers", description: "API automation testing for financial services." },
    { id: 46, title: "PHP Developer", company: "InfoEdge", location: "Noida", mode: "Hybrid", experience: "1-3", skills: ["PHP", "Laravel", "MySQL"], source: "Naukri", postedDaysAgo: 4, salaryRange: "6–10 LPA", applyUrl: "https://www.infoedge.in/careers", description: "Backend development for Naukri.com and other portals." },
    { id: 47, title: "Machine Learning Engineer", company: "InMobi", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "TensorFlow", "Ads Tech"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "18–26 LPA", applyUrl: "https://www.inmobi.com/company/careers", description: "Improve ad targeting algorithms using ML." },
    { id: 48, title: "Ruby on Rails Developer", company: "Gojek", location: "Bangalore", mode: "Remote", experience: "1-3", skills: ["Ruby", "Rails", "Postgres"], source: "LinkedIn", postedDaysAgo: 6, salaryRange: "15–25 LPA", applyUrl: "https://www.gojek.io", description: "Maintain and scale Ruby based microservices." },
    { id: 49, title: "Support Engineer", company: "Freshworks", location: "Chennai", mode: "Onsite", experience: "Fresher", skills: ["Troubleshooting", "SQL", "Communication"], source: "Careers Page", postedDaysAgo: 2, salaryRange: "4–6 LPA", applyUrl: "https://freshworks.com", description: "L1 support for global customers." },
    { id: 50, title: "Associate Product Manager", company: "UpGrad", location: "Mumbai", mode: "Onsite", experience: "0-1", skills: ["Product Management", "Analytics"], source: "LinkedIn", postedDaysAgo: 1, salaryRange: "10–15 LPA", applyUrl: "https://www.upgrad.com", description: "Assist in managing the product lifecycle for edtech courses." },
    { id: 51, title: "C++ Developer", company: "Adobe", location: "Noida", mode: "Hybrid", experience: "1-3", skills: ["C++", "Algorithms", "OS Internals"], source: "LinkedIn", postedDaysAgo: 2, salaryRange: "18–28 LPA", applyUrl: "https://adobe.com/careers", description: "Develop core features for Adobe Acrobat/Photoshop." },
    { id: 52, title: "Web Developer", company: "Zoho", location: "Tenkasi", mode: "Onsite", experience: "Fresher", skills: ["HTML", "CSS", "JS"], source: "Zoho Careers", postedDaysAgo: 5, salaryRange: "3–5 LPA", applyUrl: "https://zoho.com", description: "Build web pages and tools for internal use." },
    { id: 53, title: "Cloud Engineer", company: "Searce", location: "Pune", mode: "Hybrid", experience: "1-3", skills: ["GCP", "Terraform", "Kubernetes"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "8–12 LPA", applyUrl: "https://searce.com", description: "Cloud infrastructure automation and management." },
    { id: 54, title: "DevOps Intern", company: "Nvidia", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Python", "Linux", "Bash"], source: "Campus", postedDaysAgo: 1, salaryRange: "₹50k/month Internship", applyUrl: "https://nvidia.com/careers", description: "Automate workflows for GPU driver testing." },
    { id: 55, title: "Testing Engineer", company: "Msys", location: "Chennai", mode: "Onsite", experience: "Fresher", skills: ["Manual Testing", "Linux"], source: "Naukri", postedDaysAgo: 4, salaryRange: "3–4 LPA", applyUrl: "https://msystechnologies.com", description: "QA for storage and networking products." },
    { id: 56, title: "Angular Developer", company: "UST Global", location: "Trivandrum", mode: "Onsite", experience: "1-3", skills: ["Angular", "TypeScript"], source: "Naukri", postedDaysAgo: 2, salaryRange: "5–8 LPA", applyUrl: "https://ust.com", description: "Frontend development for healthcare clients." },
    { id: 57, title: "Data Scientist", company: "Myntra", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["Python", "ML", "SQL"], source: "LinkedIn", postedDaysAgo: 0, salaryRange: "16–24 LPA", applyUrl: "https://myntra.com/careers", description: "Fashion forecasting models and personalization." },
    { id: 58, title: "Security Engineer", company: "Flipkart", location: "Bangalore", mode: "Hybrid", experience: "1-3", skills: ["AppSec", "Burp Suite"], source: "LinkedIn", postedDaysAgo: 3, salaryRange: "15–25 LPA", applyUrl: "https://flipkart.com", description: "Identify and mitigate security vulnerabilities." },
    { id: 59, title: "Game Developer", company: "Games24x7", location: "Mumbai", mode: "Onsite", experience: "1-3", skills: ["Unity", "C#"], source: "Naukri", postedDaysAgo: 1, salaryRange: "12–18 LPA", applyUrl: "https://games24x7.com", description: "Develop logic for real money gaming apps." },
    { id: 60, title: "IT Support", company: "Dell", location: "Bangalore", mode: "Onsite", experience: "Fresher", skills: ["Hardware", "Windows"], source: "Naukri", postedDaysAgo: 6, salaryRange: "3–4 LPA", applyUrl: "https://dell.com", description: "Internal IT helpdesk support." }
];
